/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan
 */
public class vOTW extends javax.swing.JFrame {
    
    public static String nama_montir;
    public static String id_montir;
    public static String rating;
    /**
     * Creates new form vRating
     */
    public vOTW() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setSize(360, 640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lMaps = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        bMainMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lMontir = new javax.swing.JLabel();
        lNamaMontir = new javax.swing.JLabel();
        lIDMontir = new javax.swing.JLabel();
        lRating = new javax.swing.JLabel();
        lAngkaRating = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lTujuan = new javax.swing.JLabel();
        lCapWaktuTiba = new javax.swing.JLabel();
        lJarakMontir = new javax.swing.JLabel();
        lChat = new javax.swing.JLabel();
        lCall = new javax.swing.JLabel();
        lSelesai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lMaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/Screenshot_2019-12-01-17-57-59-314_0.jpg"))); // NOI18N

        bBatal.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bBatal.setText("BATAL");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bMainMenu.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bMainMenu.setText("MAIN MENU");
        bMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMainMenuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lMontir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/mechanic 2.png"))); // NOI18N

        lNamaMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lNamaMontir.setText("Jack Kahuna");

        lIDMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lIDMontir.setText("MO-001");

        lRating.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lRating.setForeground(new java.awt.Color(153, 153, 153));
        lRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/yrating.png"))); // NOI18N

        lAngkaRating.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lAngkaRating.setText("4.5 / 5.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMontir)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIDMontir)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lRating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lAngkaRating))
                    .addComponent(lNamaMontir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lNamaMontir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lIDMontir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lRating)
                            .addComponent(lAngkaRating)))
                    .addComponent(lMontir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        lTujuan.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lTujuan.setText("Montir dalam perjalanan");

        lCapWaktuTiba.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lCapWaktuTiba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/stopwatch.png"))); // NOI18N
        lCapWaktuTiba.setText(" 4 Menit");

        lJarakMontir.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lJarakMontir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/path-a-to-b.png"))); // NOI18N
        lJarakMontir.setText(" 1,7 km");

        lChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/chat.png"))); // NOI18N

        lCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/telephone.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lCall))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTujuan)
                            .addComponent(lJarakMontir)
                            .addComponent(lCapWaktuTiba))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTujuan)
                .addGap(18, 18, 18)
                .addComponent(lCapWaktuTiba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lJarakMontir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lChat)
                    .addComponent(lCall))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lMaps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMainMenuActionPerformed
        
    }//GEN-LAST:event_bMainMenuActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        
    }//GEN-LAST:event_bBatalActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bMainMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lAngkaRating;
    private javax.swing.JLabel lCall;
    private javax.swing.JLabel lCapWaktuTiba;
    private javax.swing.JLabel lChat;
    private javax.swing.JLabel lIDMontir;
    private javax.swing.JLabel lJarakMontir;
    private javax.swing.JLabel lMaps;
    private javax.swing.JLabel lMontir;
    private javax.swing.JLabel lNamaMontir;
    private javax.swing.JLabel lRating;
    private javax.swing.JLabel lSelesai;
    private javax.swing.JLabel lTujuan;
    // End of variables declaration//GEN-END:variables
     public JLabel getlCall() {
        return lCall;
    }

    public JLabel getlChat() {
        return lChat;
    }

    public JButton getbBatal(){
        return bBatal;
    }

    public JButton getbMainMenu() {
        return bMainMenu;
    }

    public void setlIDMontir(String lID) {
        lIDMontir.setText(lID);
    }

    public void setlNamaMontir(String nm) {
        lNamaMontir.setText(nm);
    }

    public void setlAngkaRating(String rate) {
        lAngkaRating.setText(rate);
    }

    
    
    

    public String getlIDMontir() {
        return lIDMontir.getText();
    }

    /**
     * @param args the command line arguments
     */
    public String getlNamaMontir() {
        return lNamaMontir.getText();
    }

    public JLabel getlSelesai() {
        return lSelesai;
    }

    public void addActionListener(ActionListener e) {
        bBatal.addActionListener(e);
        bMainMenu.addActionListener(e);
//        bSelesai.addActionListener(e);
    }
    
    @Override
    public void addMouseListener(MouseListener e) {
        lSelesai.addMouseListener(e);
        lCall.addMouseListener(e);
        lChat.addMouseListener(e);
//        bSelesai.addActionListener(e);
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
}
