/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.cOTW;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan
 */
public class vPilih extends javax.swing.JFrame {

    /**
     * Creates new form vPilih
     */
    public vPilih() {
        initComponents();
        this.setLocationRelativeTo(null);
        //setSize(360, 640);
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMontir = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbM3 = new javax.swing.JRadioButton();
        lmaps = new javax.swing.JLabel();
        rbM1 = new javax.swing.JRadioButton();
        rbM2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPilihMontir = new javax.swing.JTextArea();
        bPesan = new javax.swing.JButton();
        bBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bgMontir.add(rbM3);
        rbM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbM3ActionPerformed(evt);
            }
        });

        lmaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/Screenshot_2019-12-01-15-23-09-939 2.jpg"))); // NOI18N
        lmaps.setText("jLabel1");

        bgMontir.add(rbM1);
        rbM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbM1ActionPerformed(evt);
            }
        });

        bgMontir.add(rbM2);
        rbM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbM2ActionPerformed(evt);
            }
        });

        taPilihMontir.setColumns(20);
        taPilihMontir.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        taPilihMontir.setRows(5);
        taPilihMontir.setText("\nJack Kahuna\nRating: 4.5 / 5.0\n__________________________________\n\nZit Tooya\nRating: 4.3 / 5.0\n__________________________________\n\nCraig Mammalton\nRating: 4.4 / 5.0");
        jScrollPane1.setViewportView(taPilihMontir);

        bPesan.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bPesan.setText("PESAN");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        bBack.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        bBack.setText("BACK");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbM1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rbM3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(rbM2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lmaps, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lmaps, javax.swing.GroupLayout.PREFERRED_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbM1)
                        .addGap(51, 51, 51)
                        .addComponent(rbM2)
                        .addGap(51, 51, 51)
                        .addComponent(rbM3)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbM2ActionPerformed

    private void rbM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbM1ActionPerformed

    private void rbM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbM3ActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
//        if(get_BtMontir()==null){
//            this.showMessage("Belum Memilih Montir","Error",0);
//        }else{
//            vOTW otw =  new vOTW();
//            otw.setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_bPesanActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
//        vPesan pesan = new vPesan();
//        pesan.setVisible(true);
//        this.dispose();

    }//GEN-LAST:event_bBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public ButtonGroup getBtMontir() {
        return bgMontir;
    }
    
    
    
    
    public String get_BtMontir() {
        if(rbM1.isSelected()){
//            vOTW.nama_montir = "Jack Kahuna";
//            vOTW.id_montir = "MO-001";
//            vOTW.rating = "4.5 / 5.0";
            return "Jack";
        }else if(rbM2.isSelected()){
//            vOTW.nama_montir = "Zit Tooya";
//            vOTW.id_montir = "MO-002";
//            vOTW.rating = "4.3 / 5.0";
            return "Zit";
        }else if(rbM3.isSelected()){
//            vOTW.nama_montir = "Craig Mammalton";
//            vOTW.id_montir = "MO-003";
//            vOTW.rating = "4.4 / 5.0";
            return "Craig";
        }else return null;
    }
    
    public String getRbM1() {
        return rbM1.getText();
    }

    public String getRbM2() {
        return rbM2.getText();
    }
    
    public String getRbM3() {
        return rbM3.getText();
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public void addActionListener(ActionListener e){
        bBack.addActionListener(e);
        bPesan.addActionListener(e);
    }

    public JButton getbBack() {
        return bBack;
    }

    public JButton getbPesan() {
        return bPesan;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bPesan;
    private javax.swing.ButtonGroup bgMontir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lmaps;
    private javax.swing.JRadioButton rbM1;
    private javax.swing.JRadioButton rbM2;
    private javax.swing.JRadioButton rbM3;
    private javax.swing.JTextArea taPilihMontir;
    // End of variables declaration//GEN-END:variables
    
}
